item{0: 'Tomato', 1: 'Peach', 2: 'Apple', 3: 'Squash', 4: 'Strawberry', 5: 'Orange', 6:'Soybean', 7:'Potato', 8:'Raspberry', 9:'Pepper,', 10:'Grape', 11: 'background', 12:'Blueberry', 13:'Cherry', 14:'Corn'}